# ===============================
# SERVER CONFIG
# ===============================
server.port=8082
spring.application.name=PolicyService

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/smartsure_policy_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=pramod280504
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# CONNECTION POOL (Hikari - OPTIMIZED)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# JWT CONFIG (VERY IMPORTANT)
# ===============================
jwt.secret=mysupersecretkeymysupersecretkey12345
jwt.expiration=3600000

# ===============================
# SWAGGER / OPENAPI CONFIG
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# ===============================
# SCHEDULER
# ===============================
spring.task.scheduling.pool.size=5

# ===============================
# EUREKA (DISABLED FOR NOW)
# ===============================
eureka.client.enabled=false


# ACTUATOR

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always